#!/bin/sh

PREREQ=""
prereqs()
{
    echo "$PREREQ"
}

case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

echo "Copying kmfs script"
copy_file ${CONFDIR}/scripts/kmfs /scripts/
echo "Copying tdx-attest.conf"
cp ${CONFDIR}/tdx-attest.conf ${DESTDIR}/etc/

cp ${TDX_KO} ${DESTDIR}/${MODULESDIR}/

copy_exec /usr/sbin/mkfs.ext4 /usr/sbin
copy_exec ${CMD_IOHASH} /usr/local/bin/
copy_exec ${CMD_TDXCTL} /usr/local/bin/
copy_exec `which wget` /usr/local/bin/real_wget
copy_exec `which jq` /usr/local/bin/
copy_exec `which curl` /usr/local/bin/

auto_add_modules base ata net
