#!/bin/sh

PREREQ=""
prereqs()
{
    echo "$PREREQ"
}

case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

echo "Copying kmfs script"
copy_file ${CONFDIR}/scripts/kmfs /scripts/

cp ${TDX_KO} ${DESTDIR}/${MODULESDIR}/

copy_exec /usr/sbin/mkfs.ext4 /usr/sbin
copy_exec ${CMD_IOHASH} /usr/bin/
copy_exec ${CMD_TDXCTL} /usr/bin/
copy_exec `which wget` /usr/bin/
copy_exec `which jq` /usr/bin/

auto_add_modules base ata net
