/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DstackApp } from "./DstackApp";
export type { DstackKms } from "./DstackKms";
export type { IAppAuth } from "./IAppAuth";
export type { IAppAuthBasicManagement } from "./IAppAuthBasicManagement";
