FROM gramineproject/gramine:v1.5@sha256:615849089db84477f03cd13209c08eaf6b6a3a68b4df733e097db56781935589

RUN apt-get update && apt-get install -y \
    git=1:2.25.1-1ubuntu3.14 \
    build-essential=12.8ubuntu1.1 \
    && rm -rf /var/lib/apt/lists/*

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain 1.80 -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Set environment variables
ENV SGX=1
ENV DEBUG=0
ENV DEV_MODE=0
ENV GRAMINE=gramine-sgx
ENV RUST_LOG=info

# Clone and checkout the repository
RUN git clone https://github.com/MoeMahhouk/gramine-sealing-key-provider && \
    cd gramine-sealing-key-provider && \
    git checkout 6b4658d3d2158615b6c78879ad61612885372712

WORKDIR /gramine-sealing-key-provider
COPY Cargo.lock .

# Build key provider, generate keys, and build manifest
RUN make target/release/gramine-sealing-key-provider && \
    gramine-sgx-gen-private-key && \
    make RUST_LOG=info

RUN gramine-sgx-sigstruct-view --output-format json gramine-sealing-key-provider.sig

# Create an entrypoint script for the key provider only
COPY entrypoint-key-provider.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"] 