/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AppAuth } from "./AppAuth";
export type { IAppAuthBasicManagement } from "./IAppAuthBasicManagement";
